name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx-intl

      - name: Update .po files from .pot file
        run: |
          # Assuming the .pot file is named with the language code
          sphinx-intl update -p doc/locale -l sl
          #display pot file
          cat locales/sl/LC_MESSAGES/sl.po
          #update timestamp
          touch locales/sl/LC_MESSAGES/sl.po

      - name: Compile .po to .mo files
        run: |
          sphinx-intl build

      - name: Sphinx build with translations
        run: |
          sphinx-build -D language=sl doc _build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
          cname: gji-docs.level2.si
